### ISSUE TITLE
[REFACTOR] 온보딩 Page 수정

### ISSUE THREAD

**Issue by HyeonChae1104** [kakao-tech-campus-2nd-step3/Team16_FE#116]
## 구현 기능 설명
온보딩 페이지 구현 시 이후에 변경하겠다고 했던 사항들을 수정해보겠습니다.

## TODO
- [ ]  온보딩 화면 사진 4장 실제 구현한 것으로 변경
- [ ]  스타일링 부분 기존에 만들어둔 breakpoint를 사용하는 것으로 변경
- [ ]  카카오로그인 버튼에 누락된 카카오로고 삽입
