### ISSUE TITLE
[FEAT] Join 페이지 레이아웃

### ISSUE THREAD

**Issue by Da-Yeon-Kim** [kakao-tech-campus-2nd-step3/Team16_FE#61]
## 구현 기능 설명
Join 페이지의 레이아웃을 미리 꾸미고 그에 맞추어 폴더 구조를 정리합니다.
기존에 만들어둔 컴포넌트를 가져와 사용합니다. (기능 구현은 아직)

## TODO
- [x] 페이지 내 컴포넌트 분리 및 배치
- [x] 캘린더 컴포넌트 가져오기
- [x] 버튼 컴포넌트 가져오기
- [x] 음식 컴포넌트 가져오기 (아직 없음)
