### ISSUE TITLE
[FEAT] Join 캘린더 구현

### ISSUE THREAD

**Issue by Da-Yeon-Kim** [kakao-tech-campus-2nd-step3/Team16_FE#63]
## 구현 기능 설명
Join 페이지 내 캘린더의 기능을 구현합니다.

## TODO
- [x] 시간표의 일정을 회색으로 표시하기
- [x] API 통해 시간 범위, 모임 이름 받아오기
- [x] 시간 범위 만큼만 캘린더 보여주기
- [x] 모임 이름 보여주기
