### ISSUE TITLE
[FEAT] MyPage의 내프로필 보여주기 구현

### ISSUE THREAD

**Issue by HyeonChae1104** [kakao-tech-campus-2nd-step3/Team16_FE#64]
## 구현 기능 설명
MyPage의 '내프로필'을 구현합니다. 
프로필사진과 이름 정보를 불러오는 '프로필 조회' 부분을 구현합니다.

## TODO
- [x] 헤더의 프로필을 누르면 마이페이지로
- [x] 마이 페이지 - 프로필 사진 가져오기
- [x] 마이페이지 - 이름 정보 가져오기
