### ISSUE TITLE
[FEAT] 참여하기 버튼 로직

### ISSUE THREAD

**Issue by Da-Yeon-Kim** [kakao-tech-campus-2nd-step3/Team16_FE#81]
## 구현 기능 설명
Join 페이지의 [참여하기] 버튼의 로직을 구현합니다!

## TODO
- [x] [참여하기] 버튼 클릭 시, 백에게 데이터 전달
- [x] 데이터 전달 후, 해당 `meetingId`의 group 페이지로 이동
- [x] (추가) `WeeklyCalendar` 시간 복수 선택 가능하게 수정 + 전달 데이터에 포함
